twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'
    paths:
        '%kernel.project_dir%/public/theme/skeleton': ''
        # '%kernel.project_dir%/public/theme/%general.theme%': ''
