#controllers:
#    resource: '../src/Controller/'
#    type: annotation

controllers_with_locale:
    resource: '../src/Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
